# Generated by Django 3.1.7 on 2021-03-06 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0002_auto_20210306_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='password',
        ),
        migrations.AddField(
            model_name='workspace',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkspaceToken',
        ),
    ]
