# Generated by Django 3.1.7 on 2021-03-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_auto_20210306_2150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="nickname",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
