# Generated by Django 3.1.7 on 2021-03-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0006_workspace_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="emailed_expires",
            field=models.BooleanField(default=False),
        ),
    ]
