# Generated by Django 3.1.7 on 2021-03-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_auto_20210310_0537'),
        ('workspaces', '0007_workspace_emailed_expires'),
    ]

    operations = [
    ]
