# Generated by Django 3.1.7 on 2021-03-20 19:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210311_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceuser',
            name='nickname',
            field=models.CharField(default=users.models.get_random_unique_nickname, max_length=150, unique=True),
        ),
    ]
