version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
      - tusd
  backend:
    build:
      context: .
      dockerfile: ./docker/backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  frontend:
    build:
      context: ./Frontend
      dockerfile: ./docker/frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
  tusd:
    image: tusproject/tusd
    ports:
      - "1080:1080"
    command: -hooks-http http://backend:8000/tusd/ -max-size 10485760 -hooks-http-forward-headers Authorization
  etherpad:
    build: etherpad-lite
    ports:
      - "9001:9001"
    volumes:
      - ./docker/etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    environment:
      DEFAULT_PAD_TEXT: "hello\n"
      SOFFICE: "/usr/bin/soffice"
