version: "3.9"

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
      - tusd
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.production
    # command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
    environment:
      - "MODULE_NAME=synchronous.asgi"
      - "VARIABLE_NAME=application"
      - "PORT=8000"
      - "PRODUCTION=1"
    ports:
      - "8000:8000"
  tusd:
    image: tusproject/tusd
    ports:
      - "1080:1080"
    command: -hooks-http http://backend:8000/tusd/ -max-size 10485760 -hooks-http-forward-headers Authorization -behind-proxy
  etherpad:
    build: etherpad-lite
    ports:
      - "9001:9001"
    volumes:
      - ./docker/etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
    environment:
      DEFAULT_PAD_TEXT: "hello\n"
      SOFFICE: "/usr/bin/soffice"
      ADMIN_PASSWORD: "admin"
  spacedeck:
    build: spacedeck-open
    ports:
      - "9666:9666"
