version: "3"

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "30000:80"
    volumes:
      - ./nginx-production.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - tusd
  redis:
    image: redis
  db:
    image: postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./init-pg-dbs.sh:/docker-entrypoint-initdb.d/init-pg-dbs.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    env_file:
      - secrets.env
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.production
    restart: always
    environment:
      - "MODULE_NAME=synchronous.asgi"
      - "VARIABLE_NAME=application"
      - "PORT=8000"
      - "PRODUCTION=1"
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - secrets.env
  tusd:
    image: tusproject/tusd
    restart: always
    ports:
      - "1080:1080"
    command: -hooks-http http://backend:8000/tusd/ -max-size 10485760 -hooks-http-forward-headers Authorization -behind-proxy
  etherpad:
    build: etherpad-lite
    entrypoint: /custom-entrypoint.sh
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - ./docker/etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      - ./docker/etherpad/custom-entrypoint.sh:/custom-entrypoint.sh
    environment:
      SOFFICE: "/usr/bin/soffice"
      DB_TYPE: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "etherpad"
      DB_USER: "etherpad"
    depends_on:
      - db
    env_file:
      - secrets.env
  spacedeck:
    build: spacedeck-open
    restart: always
    ports:
      - "9666:9666"
    depends_on:
      - db
    env_file:
      - secrets.env
